### PR TITLE
Stop building w/ VS2017 in CI

### PR DESCRIPTION
**Pull request by dougbu**
- version of VisualStudio is out of support

### CODE REVIEW

**Comment by dougbu** [comment]
@smitpatel @bricelam @ajcvickers will 'main' ever build again in this repo❔ I'm wondering whether it needs this and some broader changes.

**Review by wtgodbe — APPROVED** [review]

**Comment by dougbu** [comment]
@smitpatel @bricelam @ajcvickers any reason to delay merging this❔

I also think I answered my earlier question: 'main' needs to change because it builds fairly frequently due to its stream of dependency update PRs.

**Comment by smitpatel** [comment]
No reason to delay. Can merge as long as branches are open.

**Comment by dougbu** [comment]
> Can merge as long as branches are open.

Thanks @smitpatel but my question was really whether the release/6.4 branch was open. I am not sure of the EF team's policies here.

**Comment by smitpatel** [comment]
Branch open, we don't release from it (not sure if we are planning to release in future either). I think we also need to set up few more things in this branch if we want to release a package out of it.

**Pull request merged**
