### PR TITLE
Fix resource loader issue

### LINKED ISSUE #2141: Resource loader Bug in M.E.S.
See https://github.com/ErikEJ/EntityFramework6PowerTools/issues/131

### PR DESCRIPTION
**Pull request by ErikEJ**
fixes #2141

### CODE REVIEW

**Comment by ErikEJ** [comment]
@bricelam should I retarget this?

**Comment by bricelam** [comment]
Do we really need to copy Resources.SqlServer.resx? Can't we just compile the original one with the correct embedded name?

**Comment by bricelam** [comment]
> @bricelam should I retarget this?

Nah, I'll make sure it gets merged correctly.

**Comment by ErikEJ** [comment]
@bricelam yeah, I have a feeling someone smarter than me could do this better...

**Review by bricelam — APPROVED** [review]
I'll play with it for a minute or two before merging, but I'm also fine just copying it.

**Comment by ErikEJ** [comment]
@bricelam Let me know if there is anything I can do to help

**Comment by ErikEJ** [comment]
@ajcvickers @bricelam Has the plans for a release been abandoned?

**Comment by bricelam** [comment]
Some internal tools are really struggling with the fact that we target .NET Core 3.1. PR #2140 was an attempt to make them happy, but it didn't work.

**Comment by ErikEJ** [comment]
But you do not target .NET 3.1 any more?? Do you mean netstandard 2.1 ??

**Comment by bricelam** [comment]
🤷‍♂️ Something is causing Microsoft.NETCore.App.Runtime.win-arm64 version 3.0.3 to be downloaded during build...

**Comment by ErikEJ** [comment]
And that is no longer available in your internal feeds?

**Comment by bricelam** [comment]
> And that is no longer available in your internal feeds?

Oh no, everything is functional. It's just the usual bureaucratic red tape keeping us from shipping.

**Comment by bricelam** [comment]
(Updated to use the original .resx file)

**Comment by ErikEJ** [comment]
@bricelam It is the ef6 CLI!

```xml
<PropertyGroup>
  <OutputType>Exe</OutputType>
  <TargetFrameworks>netcoreapp3.0;net40;net45</TargetFrameworks>
  <RuntimeIdentifiers>win-arm64</RuntimeIdentifiers>
  <CheckEolTargetFramework>False</CheckEolTargetFramework>
  <RootNamespace>System.Data.Entity.Tools</RootNamespace>
  <!--
    This keeps ef6.exe targeting the default version of .NET Core for netcoreapp3.0,
    which maximizes the machines on which this tool will be compatible.
  -->
  <TargetLatestDotNetRuntime Condition=" '$(IsServicingBuild)' == 'true' ">false</TargetLatestDotNetRuntime>
</PropertyGroup>

<ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'">
  <Reference Include="Microsoft.CSharp" />
  <Reference Include="System.Windows.Forms" />
</ItemGroup>
```

**Pull request merged**
