### PR TITLE
Switch to 5.0.0-preview1 branding

### PR DESCRIPTION
**Pull request by wtgodbe**
Part of dotnet/aspnetcore#18789

CC @dotnet/aspnet-build @mmitche

### CODE REVIEW

**Comment by mmitche** [comment]
> Looks fine but I believe (hope?) the resulting branding will be 5.0.0-preview.1

It won't, because ef6 is using semantic versioning v1: https://github.com/dotnet/ef6/blob/master/eng/Versions.props#L6

Should this be changed?

**Comment by mmitche** [comment]
So actually, what should happen is one of two things:
- Switch off semver1 (I have no idea why this is the case today, maybe @bricelam knows?)
- Change the pre-release label to 'preview1' and remove the `PrereleaseVersionIteration` property.

I think the first option is better.

**Comment by dougbu** [comment]
> Switch off semver1 (I have no idea why this is the case today, maybe @bricelam knows?)

@dotnet/efcore in case @bricelam is disconnected again today.

**Comment by bricelam** [comment]
Keep using semver1. There's no reason to break older NuGet clients--the runtime should continue to work on .NET Framework 4.0

**Comment by mmitche** [comment]
> Keep using semver1. There's no reason to break older NuGet clients--the runtime should continue to work on .NET Framework 4.0

Which version of nuget comes with that? 4.3 is when semver2 support came in. That's from 8/2017.

**Comment by mmitche** [comment]
Also, .NET Framework 4.0 is out of support. It ended in 2016. This sounds like an odd reason to keep semver1

**Comment by ajcvickers** [comment]
@mmitche At the time we ported EF6 to Core we considered removing some of the older targets. Hunter said we needed to show it would have minimal customer impact. Initial investigation indicated that it would impact significant number of people. Therefore we still target net40 and we still work with very old NuGet.

We could revisit this, but we would have to get Hunter to change his mind.

**Comment by ajcvickers** [comment]
Fundamentally, I think the problem here is we're trying to treat EF6 like it is part of the .NET Core wave, because that's what the build infrastructure, etc. is designed for. But EF6 isn't that. It's a legacy product that happens to have a Core version.

**Comment by mmitche** [comment]
Got it. Odd that people are upgrading to new versions of EF6 on ancient versions of the framework. Do we test on that?

Given this, I want to change arcade so that it makes "preview1" automatically given a PrereleaseVersionIteration + PrereleaseVersionLabel for semver1, so that the methodology to update branding during previews is consistent across the stack. Hold on this PR until you get an upgraded arcade version with this feature.

**Comment by ajcvickers** [comment]
@bricelam @dotnet/aspnet-build We should probably also discuss the EF6 build in the meeting we have scheduled for the Core 5.0 build.

**Comment by mmitche** [comment]
> @bricelam @dotnet/aspnet-build We should probably also discuss the EF6 build in the meeting we have scheduled for the Core 5.0 build.

Ya, I also noticed that you don't target netcoreapp5.0, so today IMO ef6 could be pretty much a completely independent repo.

**Comment by wtgodbe** [comment]
This won't ship with 5, so we don't need to update its branding along with the other repos

**Comment by mmitche** [comment]
> This won't ship with 5, so we don't need to update its branding along with the other repos

No previews at all in the 5 train?

**Comment by wtgodbe** [comment]
> No previews at all in the 5 train?

That's the decision we came to today (CC @ajcvickers @Pilchie)

**Pull request closed without merging**
