### PR TITLE
Migrate license from Apache -> MIT

### PR DESCRIPTION
**Pull request by Pilchie**

### CODE REVIEW

**Comment by Pilchie** [comment]
Tagging @ChrisSfanos.

**Review by ajcvickers — APPROVED** [review]

**Comment by dougbu** [comment]
Status @Pilchie ❔

**Comment by Pilchie** [comment]
It's ready to go, but we decided to wait to merge until we have another reason to ship an EF6 release.

**Comment by ajcvickers** [comment]
We're planning one for later in the year, so we can do it then.

**Pull request merged**
