### PR TITLE
Target .NET 6.0 with ef6

### PR DESCRIPTION
**Pull request by ErikEJ**

### CODE REVIEW

**Comment by ErikEJ** [comment]
@bricelam What do you think? No more net3.x any more at least!

**Comment by bricelam** [comment]
Hmm, it's a breaking change, but 3.1 and 5.0 are out of support, so maybe it's acceptable. Let me see if it avoids downloading the problematic DLLs. If it does, I'll discuss it with the team.

**Comment by ErikEJ** [comment]
Looking forward to the outcome!

**Comment by ErikEJ** [comment]
@bricelam  Just verified that 3.0.3 is no longer downloaded:

In artifacts\obj\ef6\project.assets.json

```json
        "downloadDependencies": [
          {
            "name": "Microsoft.AspNetCore.App.Runtime.win-arm64",
            "version": "[6.0.23, 6.0.23]"
          },
          {
            "name": "Microsoft.NETCore.App.Runtime.win-arm64",
            "version": "[6.0.23, 6.0.23]"
          },
          {
            "name": "Microsoft.WindowsDesktop.App.Runtime.win-arm64",
            "version": "[6.0.23, 6.0.23]"
          }
        ],
        "frameworkReferences": {
          "Microsoft.NETCore.App": {
            "privateAssets": "all"
          }
        },
```

**Comment by ErikEJ** [comment]
@bricelam ,Did you reach a conclusion? 😉

**Comment by bricelam** [comment]
Met yesterday. We all agree it's OK to make this breaking change.

**Comment by ErikEJ** [comment]
Wauw - you made my day! 😄

**Comment by bricelam** [comment]
lol, I'm trying not to get my hopes up. Every time I think we're close to releasing, something seems to go wrong. 🤞

**Comment by bricelam** [comment]
Well, we fixed one of the issues. Two more to go... ☹️

**Comment by ErikEJ** [comment]
@bricelam Let me know if I can help

**Comment by bricelam** [comment]
One of the errors is related to https://github.com/dotnet/efcore/pull/32108, so that should eventually get resolved. I'll work on resolving the remaining error.

**Comment by ErikEJ** [comment]
@David-Engel Was a 5.1.3 release with an updated Azure.Identity planned? And if so, when?

@bricelam Will adding an explicit reference fix this?

**Comment by bricelam** [comment]
Yay, PR #2175 fixed the other issue.

>Will adding an explicit reference fix this?

It would make the error go away, but no, I wouldn't say it fixes the actual issue.

**Pull request merged**
