### PR TITLE
fix for broken NuGet package

### LINKED ISSUE #2262: EF 6.5.0 RTM NuGet Package BROKEN
# RTM PACKAGE FAILURE

There is an error in the package for 6.5.0 that has broken the EF build process in Visual Studio. The package is not being built properly, therefore `EntityDeploy` is no longer being called to compile EDMX files into the project.

👉🏻 **For people experiencing this issue, there is a temporary workaround, see below.** 👈🏻

## SYMPTOMS:
You will suddenly get a "Metadata cannot be loaded" error in any project that leverages the `DbContext`, where the code previously functioned normally.

## IMPACT
Automated builds that were previously working are now failing. I spent several hours tracking down why my services suddenly stopped working.

## NEEDED RESOLUTION
- [ ] **EntityFramework 6.5.0 package must be deprecated on NuGet.org IMMEDIATELY**
- [ ] Revert the change from Preview 2 that broke the build folder
- [ ] The release process should be validating the package contents before deploying the package

## EVIDENCE
New EntityFramework 6.5.0 RTM vs EntityFramework 6.4.4 RTM packages:

image
image

## WORKAROUND
In the project with your EDMX file, replace your `<PackageReference Include="EntityFramework" ... />` line with the following entries:

```xml
        <PackageReference Include="Microsoft.EntityFramework.SqlServer" Version="6.*" />
        <PackageReference Include="EntityFramework" Version="6.4.*" ExcludeAssets="compile,runtime" NoWarn="NU1605" />
```
This will tell the build process to use the `EntityCompile` tasks from the EF 6.4.4 package, [but NOT to reference anything in the `lib` folder for compilation](https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets). That means the downstream reference to `EntityFramework` 6.5 from the `Microsoft.EntityFramework.SqlServer` package will still get compiled into the build and your code will work correctly. The "NoWarn" attribute will tell the build process not to complain that you're referencing a version that the `.SqlServer` package doesn't like.

### PR DESCRIPTION
**Pull request by ErikEJ**
fixes #2262

@AndriySvyryd FYI 😭

### CODE REVIEW

**Review by AndriySvyryd — APPROVED** [review]

**Comment by ErikEJ** [comment]
I have verified/reproduced locally that this change broke the package

**Comment by AndriySvyryd** [comment]
@ErikEJ Please rebase on `release/6.5`

**Comment by ErikEJ** [comment]
@AndriySvyryd How do I do that from my branch? (Excuse my ignorance) - with git cli

**Comment by AndriySvyryd** [comment]
Something like `git rebase upstream/release/6.5 -i`
Assuming that the remote for this repo is called `upstream`

**Comment by ErikEJ** [comment]
@AndriySvyryd That di not go so well - let me start over

**Comment by birbilis** [comment]
got bit too by the previous NuGet package (wasn't removing old entries from files and was also creating some configuration subfolders), had to rollback via version control and install the new one which works fine (upgrading to new package wasn't solving the mess). Maybe rolling back to previous NuGet package might have worked too, but not sure

**Pull request merged**
