### PR TITLE
Update SqlClient(s)

### PR DESCRIPTION
**Pull request by ErikEJ**
/cc @ajcvickers

### CODE REVIEW

**Review by ajcvickers — APPROVED** [review]

**Comment by ErikEJ** [comment]
thanks @ajcvickers - any plans to attempt a 6.5 build again - or must we wait for 5.1.5 🤯 ??

**Comment by ajcvickers** [comment]
I'm leaving that up to the new manager.

**Comment by lyndaidaii** [comment]
Can we build package? We have CG alert, however, our Gallery repo is blocked by entity framework packages.

**Comment by ErikEJ** [comment]
@lyndaidaii If you are on .NETFramework you must install the January 2024 .NET Framework update, and if you are on .NET, you can add an explicit reference to version 4.8.6

**Pull request merged**
