### PR TITLE
[release/6.5] Onboard the official build to 1ES pipeline templates

### PR DESCRIPTION
**Pull request by AndriySvyryd**

### CODE REVIEW

**Comment by dougbu** [comment]
@AndriySvyryd please do not request DNCEng reviews of product pipeline changes. your team owns your YAML. we're hear to help (answering questions where we can) and to provide suitable infrastructure.

/cc @markwilkie

**Comment by SamMonoRT** [comment]
@directhex  - please can you take a look. TIA

**Review by SamMonoRT — APPROVED** [review]

**Comment by directhex** [comment]
Do we have a test build from internal CI of the new pipeline changes?

**Comment by directhex** [comment]
If it were me, I would personally reverse the major whitespace changes which the conversion tool introduces to multi-line scripts (those newlines probably existed for a reason), but eyeballing this, it seems okay. I'd want to see the private build before slapping a gold star on it.

**Comment by AndriySvyryd** [comment]
@directhex https://dev.azure.com/dnceng/internal/_build/results?buildId=2401526
The SBoM manifest error is a known issue in arcade.

**Pull request merged**
