### PR TITLE
Feature/parameter AsString

### PR DESCRIPTION
**Pull request by anthogd63**
It is very unlikely that we will accept a pull request for this repo. See the [README](https://github.com/dotnet/ef6/blob/main/README.md) for more info.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/ef6?pullRequest=2033) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/ef6?pullRequest=2033) before we can accept your contribution.<br/><br/>:x: anthogd63 [sign now](https://cla.dotnetfoundation.org/dotnet/ef6?pullRequest=2033)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/ef6?pullRequest=2033) it.</sub>

**Comment by ajcvickers** [comment]
This PR has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.

**Comment by CZEMacLeod** [comment]
This was an interesting approach to solve a problem with parameter types for string that has been brought up quite a few times. I'm not sure if this can be done using any extensibility hooks - if so, it would make a nuget package.

@ajcvickers I understand that EF6 has been dumped by MS, but there was a lot of in-progress stuff that was all closed, and a number of issues that are still relevant. I understand that resources need to be focused on 'new' technologies such as EFCore, but there is such a gap and moving to EFCore is not always an option (especially for those of us with huge Net4.8 codebases) - and even if we are trying to move to EFCore, there is no 'easy' was to port our existing customizations, models etc.
If there were some better 'shims' in place it would really help those of us in this situation, rather than leaving us in the cold with no support.

**Comment by anthogd63** [comment]
> This was an interesting approach to solve a problem with parameter types for string that has been brought up quite a few times. I'm not sure if this can be done using any extensibility hooks - if so, it would make a nuget package.
> 
> @ajcvickers I understand that EF6 has been dumped by MS, but there was a lot of in-progress stuff that was all closed, and a number of issues that are still relevant. I understand that resources need to be focused on 'new' technologies such as EFCore, but there is such a gap and moving to EFCore is not always an option (especially for those of us with huge Net4.8 codebases) - and even if we are trying to move to EFCore, there is no 'easy' was to port our existing customizations, models etc. If there were some better 'shims' in place it would really help those of us in this situation, rather than leaving us in the cold with no support.

Hello CZEMacLeod, that you for your message. You perfectly describe the situation I am faced. I have a lot of code to migrate, a huge regression risk if I move on EFCore but I haven't the bandwith or budget yet for that. So I've created this fork with very few changes, in order to provide an easy way to solve one of my main issue with ef6.
I've created a nuget package from my code that is fully compatible and could be integrated easily. If you are interested, I can provide you this package. Don't hesitate to contact me :)

**Pull request closed without merging**
